// Generated by CoffeeScript 1.6.3
var contactMessages;

contactMessages = [];

module.exports = {
  index: function(req, res) {
    var viewModel;
    viewModel = {
      title: "Home Page",
      email: "email@host.com",
      phone: "343.300.3443.30",
      contactMessages: contactMessages
    };
    return res.render("home/index.twig", viewModel);
  },
  contact: function(req, res) {
    return res.render("home/contact.twig", {
      contactMessages: contactMessages
    });
  },
  createContact: function(req, res) {
    contactMessages.push({
      message: req.body.message,
      name: req.body.name
    });
    return res.redirect("/home");
  }
};

/*
//@ sourceMappingURL=home.map
*/
