// Generated by CoffeeScript 1.6.3
module.exports = {
  /* GET home page.*/

  index: function(req, res) {
    return res.render('index.twig', {
      message: "This is mparaiso's message"
    });
  }
};

/*
//@ sourceMappingURL=index.map
*/
