// Generated by CoffeeScript 1.6.3
module.exports = {
  index: (function(req, res) {
    return req.app.locals.db.Users.find({}, function(err, docs) {
      return res.render("users/index.twig", {
        users: docs
      });
    });
  }),
  "new": (function(req, res) {
    var b;
    if (req.route.method.toLowerCase() === "post") {
      b = req.body;
      return new req.app.locals.db.Users({
        name: b.name,
        age: b.age,
        email: b.email
      }).save(function(err, user) {
        return res.redirect("/users/" + user.name);
      });
    } else {
      return res.render("users/new.twig");
    }
  }),
  show: (function(req, res) {
    var username;
    username = req.params.name;
    return req.app.locals.db.Users.find({
      name: username
    }, function(err, docs) {
      var user;
      user = docs[0];
      return res.render("users/show.twig", {
        user: user
      });
    });
  }),
  edit: (function(req, res) {
    var db;
    db = req.app.locals.db;
    return db.Users.findById(req.params.id, (function(err, user) {
      if (req.route.method.toLowerCase() === "post") {
        return db.Users.update({
          _id: req.body.id
        }, {
          name: req.body.name,
          age: req.body.age,
          email: req.body.email
        }, function(err) {
          return res.redirect("/users/" + req.body.name);
        });
      } else {
        return res.render("users/edit.twig", {
          user: user,
          action: "/users/edit/" + user.id,
          method: "POST"
        });
      }
    }));
  }),
  list: (function(req, res) {
    return res.render("list.twig", {
      online: req.online
    });
  })
};

/*
//@ sourceMappingURL=users.map
*/
