// Generated by CoffeeScript 1.6.3
module.exports = function(container) {
  return container.share("feedparser", function(container) {
    var feedparser;
    feedparser = require('ortoo-feedparser');
    return {
      parse: function(url, options) {
        return feedparser.parseUrl(url, options);
      }
    };
  });
};

/*
//@ sourceMappingURL=feedparser.map
*/
